image: rocker/tidyverse
test:  
  script:
    - apt update
    - apt install -y systemd zlib1g-dev libjpeg-dev texlive-full qpdf
    - timedatectl set-timezone Europe/Paris
    - R -e 'install.packages(c("DiscreteWeibull","seqinr", "roxygen2", "Rcpp", "RcppArmadillo"))'
    - R CMD build --compact-vignettes=both .
    - mv smmR*.tar.gz smmR.tar.gz
    - R CMD check --as-cran smmR.tar.gz
  artifacts:
    paths:
      - smmR.tar.gz
