image: rocker/tidyverse
test:  
  script:
    - apt update
    - apt install -y zlib1g-dev libjpeg-dev texlive-full
    - R -e 'install.packages(c("DiscreteWeibull","seqinr","qpdf", "roxygen2"))'
    - cd SMM
    - R -e 'devtools::document()'
    - cd -
    - R CMD build SMM
    - mv SMM*.tar.gz SMM.tar.gz
    - R CMD check --as-cran SMM.tar.gz
  artifacts:
    paths:
      - SMM.tar.gz
      - SMM/inst/doc/smm.pdf
