image: rocker/verse
test:  
  script:
    - apt update
    - apt install -y zlib1g-dev libjpeg-dev r-cran-seqinr r-cran-qpdf r-cran-roxygen2
    - R -e 'install.packages(c("DiscreteWeibull"))'
    - cd SMM
    - R -e 'devtools::document()'
    - cd -
    - R CMD build SMM
    - mv SMM*.tar.gz SMM.tar.gz
    - R CMD check --as-cran --no-build-vignettes --no-manual SMM.tar.gz
  artifacts:
    paths:
      - SMM.tar.gz
