# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Set the RNG Seed from within Rcpp
#' 
#' @param seed A \code{unsigned int} that is the seed one wishes to use.
#' @return A set RNG scope.
#' @examples
#' set.seed(10)
#' x <- rnorm(5, 0, 1)
#' setSeed(10)
#' y <- rnorm(5, 0, 1)
#' all.equal(x, y, check.attributes = FALSE)
#' 
#' @export
#' 
setSeed <- function(seed) {
    invisible(.Call(`_SMM_setSeed`, seed))
}

